import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between p-3 overflow-hidden">
          <div>Logo</div>
          <div className="flex ">
            <Link className="px-5" href="/">
              Welcome
            </Link>

            <Link className="px-5" href="/chat_box">
              Chat Box
            </Link>

            <Link className="px-5" href="/login">
              Login
            </Link>
            <Link className="px-5" href="/register">
              Register
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
